### ISSUE TITLE
Make a web page according to basic.txt

### ISSUE THREAD

**Issue by Hj88** [Hj88/Sagarwale_Consultancy#1]
Make a web page according to basic.txt

**Comment by Badkul77** [comment]
Please assign me this issue

**Comment by hambali999** [comment]
Hi i am really interested to contribute to this project! I can make a web page according to the basic.txt

**Comment by hambali999** [comment]
Hi I will fully revamp the website into a more responsive and better looking website for your consultancy :)

**Comment by hambali999** [comment]
Hey you need to label your issues with "Hacktoberfest" for it to be eligible for the hacktoberfest2020
