### ISSUE TITLE
Make a responsive Style Sheet.

### ISSUE THREAD

**Issue by Hj88** [Hj88/Sagarwale_Consultancy#2]
Make a responsive Style Sheet using a CSS for the front dashboard with navigation at the top and footer with company name.
Some more functionality to be included are-:

1. CardView for different category.
2.Inner Scroolbar for different category.
3. Image Styling.
4.Dropdown menu for profile section.

**Comment by tarunjain1st** [comment]
Assign this to me i wanted to work

**Comment by hambali999** [comment]
Hi i will fully revamp this website into a more responsive one is that fine?
