### ISSUE TITLE
Create a contact page.

### ISSUE THREAD

**Issue by Hj88** [Hj88/Sagarwale_Consultancy#5]
Create a responsive contact page for our website using html

**Comment by r4pt0s** [comment]
Hi,
I can work on this one if you want. 
What are the requirements for this contact page?

Any kind of form and endpoint to reach?

**Comment by hambali999** [comment]
Hi! Can i work on this? this is my first hacktoberfest

**Comment by hambali999** [comment]
Hi i will create a contact page and fully revamp the website to suit the consultancy services

**Comment by hambali999** [comment]
Please assigned me

**Comment by hambali999** [comment]
Hi you need to add "hacktoberfest" as the label

**Comment by hambali999** [comment]
Hey you need to label your issues with "Hacktoberfest" for it to be eligible for the hacktoberfest2020

**Comment by Badkul77** [comment]
Please assign it to me ,I have a optimal solution for it.

**Comment by Badkul77** [comment]
okay fine i will provide you a optimal solution

**Comment by hambali999** [comment]
@Hj88 Hi i can create a contact page for you immediately
